[package]
name = "deploy-multi-chain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15"  # or the latest version
serde_json = "1.0"
toml = "0.5"  # or the latest version