name: "Deploy Lockup Linear"

env:
  API_KEY_ARBISCAN: ${{ secrets.API_KEY_ARBISCAN }}
  API_KEY_BSCSCAN: ${{ secrets.API_KEY_BSCSCAN }}
  API_KEY_ETHERSCAN: ${{ secrets.API_KEY_ETHERSCAN }}
  API_KEY_GNOSISSCAN: ${{ secrets.API_KEY_GNOSISSCAN }}
  API_KEY_INFURA: ${{ secrets.API_KEY_INFURA }}
  API_KEY_OPTIMISTIC_ETHERSCAN: ${{ secrets.API_KEY_OPTIMISTIC_ETHERSCAN }}
  API_KEY_POLYGONSCAN: ${{ secrets.API_KEY_POLYGONSCAN }}
  API_KEY_SNOWTRACE: ${{ secrets.API_KEY_SNOWTRACE }}
  FOUNDRY_PROFILE: "optimized"
  MNEMONIC: ${{ secrets.MNEMONIC }}

on:
  workflow_dispatch:
    inputs:
      admin:
        default: "0xF3663da48030b6c88535413Fd643aB0B5F3496ff"
        description: "Initial contract admin."
        required: false
      chain:
        default: "goerli"
        description: "Chain name as defined in the Foundry config."
        required: false
      comptroller:
        description: "Address of an already deployed comptroller."
        required: true
      nft-descriptor:
        description: "Address of an NFT descriptor contract."
        required: true

jobs:
  deploy-lockup-linear:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"
        with:
          submodules: "recursive"

      - name: "Install Foundry"
        uses: "foundry-rs/foundry-toolchain@v1"

      - name: "Deploy the SablierV2LockupLinear contract"
        run: >-
          forge script script/DeployLockupLinear.s.sol
          --broadcast
          --rpc-url ${{ inputs.chain }}
          --sig "run(address,address,address)"
          --verify
          "${{ inputs.admin }}"
          "${{ inputs.comptroller }}"
          "${{ inputs.nft-descriptor }}"
          -vvvv

      - name: "Add workflow summary"
        run: |
          echo "## Result" >> $GITHUB_STEP_SUMMARY
          echo "âœ… Done" >> $GITHUB_STEP_SUMMARY
