name: "Deploy NFT Descriptor"

env:
  API_KEY_ETHERSCAN: ${{ secrets.API_KEY_ETHERSCAN }}
  API_KEY_INFURA: ${{ secrets.API_KEY_INFURA }}
  FOUNDRY_PROFILE: "optimized"
  MNEMONIC: ${{ secrets.MNEMONIC }}

on:
  workflow_dispatch:
    inputs:
      chain:
        default: "goerli"
        description: 'Chain name. Defaults to "goerli" if unspecified'
        required: false

jobs:
  deploy-nft-descriptor:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"
        with:
          submodules: "recursive"

      - name: "Install Foundry"
        uses: "foundry-rs/foundry-toolchain@v1"

      - name: "Deploy the dummy NFT Descriptor"
        run: >-
          forge script script/deploy/DeployNFTDescriptor.s.sol
          --broadcast
          --rpc-url "${{ github.event.inputs.chain }}"
          -vvvv

      - name: "Add summary"
        run: |
          echo "## Deployment result" >> $GITHUB_STEP_SUMMARY
          echo "âœ… Passed" >> $GITHUB_STEP_SUMMARY
