name: "Deploy Protocol"

env:
  ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
  FOUNDRY_PROFILE: "optimized"
  INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
  MNEMONIC: ${{ secrets.MNEMONIC }}

on:
  workflow_dispatch:
    inputs:
      admin:
        default: "0x0E109f35926575FC64Ec73735101966d434Ed591"
        description: 'Contract admin. Defaults to 0x0E10...d591'
        required: false
      chain:
        default: "goerli"
        description: 'Chain name. Defaults to "goerli" if unspecified'
        required: false
      max-fee:
        default: "100000000000000000"
        description: |
          The maximum fee that can be charged by either the protocol or a broker.

          Defaults to 10%.
        required: false
      nft-descriptor:
        default: "0x0F1dE24BAe4d7523bC529EB804ED6C0B4966e1c8"
        description: "The address of the contract that produces the NFT descriptor"
        required: false
      max-segment-count:
        default: "1000"
        description: |
          The maximum number of segments permitted in a stream.

          Defaults to 1,000
        required: false

jobs:
  deploy-protocol:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"
        with:
          submodules: "recursive"

      - name: "Install Foundry"
        uses: "foundry-rs/foundry-toolchain@v1"

      - name: "Deploy the entire Sablier V2 protocol"
        run: >-
          forge script script/deploy/DeployProtocol.s.sol
          --broadcast
          --rpc-url "${{ github.event.inputs.chain }}"
          --sig "run(address,uint256,uint256)"
          -vvvv
          "${{ github.event.inputs.admin }}"
          "${{ github.event.inputs.max-fee }}"
          "${{ github.event.inputs.nft-descriptor }}"
          "${{ github.event.inputs.max-segment-count }}"

      - name: "Add summary"
        run: |
          echo "## Deployment result" >> $GITHUB_STEP_SUMMARY
          echo "âœ… Passed" >> $GITHUB_STEP_SUMMARY
