name: "Deploy Pro"

env:
  ETHERSCAN_API_KEY: "${{ secrets.ETHERSCAN_API_KEY }}"
  INFURA_API_KEY: "${{ secrets.INFURA_API_KEY }}"
  MNEMNONIC: "${{ secrets.MNEMONIC }}"

on:
  workflow_dispatch:
    inputs:
      chain:
        default: "goerli"
        description: 'Chain name, defaults to "goerli" if unspecified'
        required: false
      comptroller:
        description: "The address of the previously SablierV2Comptroller contract"
        required: true
      max-fee:
        default: "10000000000000000000"
        description: "The maximum fee that can be charged by either the protocol or a broker, defaults to 10%"
        required: false
      max-segment-count:
        default: "1000"
        description: "The maximum number of segments permitted in a stream, defaults to 1,000"
        required: false

jobs:
  ci:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"
        with:
          submodules: "recursive"

      - name: "Install Foundry"
        uses: "foundry-rs/foundry-toolchain@v1"
        with:
          version: "nightly"

      - name: "Deploy the SablierV2Pro contract"
        run: >-
          forge script script/DeployPro.s.sol
          --broadcast
          --rpc-url ${{ github.event.inputs.chain }}
          --sig "run(address,uint256,uint256)"
          "${{ github.event.inputs.comptroller }}"
          "${{ github.event.inputs.max-fee }}"
          "${{ github.event.inputs.max-segment-count }}"

      - name: "Add summary"
        run: |
          echo "## Deployment result" >> $GITHUB_STEP_SUMMARY
          echo "âœ… Passed" >> $GITHUB_STEP_SUMMARY
