name: "Deploy Lockup Linear"

env:
  API_KEY_ETHERSCAN: ${{ secrets.API_KEY_ETHERSCAN }}
  API_KEY_INFURA: ${{ secrets.API_KEY_INFURA }}
  FOUNDRY_PROFILE: "optimized"
  MNEMONIC: ${{ secrets.MNEMONIC }}

on:
  workflow_dispatch:
    inputs:
      admin:
        default: "0x0E109f35926575FC64Ec73735101966d434Ed591"
        description: 'Contract admin. Defaults to 0x0E10...d591'
        required: false
      chain:
        default: "goerli"
        description: 'Chain name. Defaults to "goerli" if unspecified'
        required: false
      comptroller:
        description: "The address of the previously SablierV2Comptroller contract"
        required: true
      nft-descriptor:
        description: "The address of the contract that generates the NFT descriptor"
        required: true

jobs:
  deploy-linear:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"
        with:
          submodules: "recursive"

      - name: "Install Foundry"
        uses: "foundry-rs/foundry-toolchain@v1"

      - name: "Deploy the SablierV2LockupLinear contract"
        run: >-
          forge script script/deploy/DeployLockupLinear.s.sol
          --broadcast
          --rpc-url ${{ github.event.inputs.chain }}
          --sig "run(address,address,uint256)"
          "${{ github.event.inputs.admin }}"
          "${{ github.event.inputs.comptroller }}"
          "${{ github.event.inputs.nft-descriptor }}"
          -vvvv

      - name: "Add summary"
        run: |
          echo "## Deployment result" >> $GITHUB_STEP_SUMMARY
          echo "âœ… Passed" >> $GITHUB_STEP_SUMMARY
