name: "Deploy Core"

env:
  API_KEY_INFURA: ${{ secrets.API_KEY_INFURA }}
  FOUNDRY_PROFILE: "optimized"
  MNEMONIC: ${{ secrets.EVM_MNEMONIC }}

on:
  workflow_dispatch:
    inputs:
      admin:
        default: "0xF3663da48030b6c88535413Fd643aB0B5F3496ff"
        description: "Initial protocol admin."
        required: false
      chain:
        default: "sepolia"
        description: "Chain name as defined in the Foundry config."
        required: false
      max-segment-count:
        default: "300"
        description: "Maximum number of segments allowed in a stream."
        required: false

jobs:
  deploy-core:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v4"

      - name: "Install Foundry"
        uses: "foundry-rs/foundry-toolchain@v1"

      - name: "Deploy the Sablier V2 Core protocol"
        run: >-
          forge script script/DeployCore.s.sol
          --broadcast
          --rpc-url "${{ inputs.chain }}"
          --sig "run(address,uint256)"
          --verify
          "${{ inputs.admin }}"
          "${{ inputs.max-segment-count }}"
          -vvvv

      - name: "Add workflow summary"
        run: |
          echo "## Result" >> $GITHUB_STEP_SUMMARY
          echo "âœ… Done" >> $GITHUB_STEP_SUMMARY
