name: "Deploy Core"

env:
  API_KEY_ETHERSCAN: ${{ secrets.API_KEY_ETHERSCAN }}
  API_KEY_INFURA: ${{ secrets.API_KEY_INFURA }}
  FOUNDRY_PROFILE: "optimized"
  MNEMONIC: ${{ secrets.MNEMONIC }}

on:
  workflow_dispatch:
    inputs:
      admin:
        default: "0x0E109f35926575FC64Ec73735101966d434Ed591"
        description: "Initial protocol admin."
        required: false
      chain:
        default: "goerli"
        description: "Chain name as defined in the Foundry config."
        required: false
      nft-descriptor:
        description: "Address of an NFT descriptor contract"
        required: true
      max-segment-count:
        default: "300"
        description: "Maximum number of segments allowed in a stream."
        required: false

jobs:
  deploy-protocol:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"
        with:
          submodules: "recursive"

      - name: "Install Foundry"
        uses: "foundry-rs/foundry-toolchain@v1"

      - name: "Deploy the Sablier V2 Core protocol"
        run: >-
          forge script script/DeployCore.s.sol
          --broadcast
          --rpc-url "${{ inputs.chain }}"
          --sig "run(address,address,uint256)"
          "${{ inputs.admin }}"
          "${{ inputs.nft-descriptor }}"
          "${{ inputs.max-segment-count }}"
          -vvvv

      - name: "Add summary"
        run: |
          echo "## Deployment result" >> $GITHUB_STEP_SUMMARY
          echo "âœ… Passed" >> $GITHUB_STEP_SUMMARY
